@echo off
set UE4RootPath=D:\UnrealEngine-4.24.2-release\
set ProjectRootPath=D:\SaveMap\
set PackageRootPath=E:\WindowsNoEditor\

set UE4BinPath=%UE4RootPath%Engine\Binaries\Win64\
set UE4PluginPath=%UE4RootPath%Engine\Plugins\
set ProjectBinPath=%ProjectRootPath%Binaries\Win64\
set ProjectPluginPath=%ProjectRootPath%Plugins\
set PackageEngineBinPath=%PackageRootPath%Engine\Binaries\Win64\
set PackageEnginePluginPath=%PackageRootPath%Engine\Plugins\
set PackageBinPath=%PackageRootPath%SaveMap\Binaries\Win64\
set PackagePluginPath=%PackageRootPath%SaveMap\Plugins\


xcopy /e /y %ProjectBinPath%UE4Editor-SaveMap-Win64-Debug.dll		 		%PackageBinPath%
xcopy /e /y %ProjectBinPath%UE4Editor-SaveMap-Win64-Debug.pdb		 		%PackageBinPath%

xcopy /e /y %UE4BinPath%UE4Editor-Win64-Debug.exe		 			%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Win64-Debug.pdb		 			%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Win64-Debug.modules		 		%PackageEngineBinPath%

xcopy /e /y %UE4BinPath%UnrealLightmass.exe									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UnrealLightmass-ApplicationCore.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UnrealLightmass-Core.dll								%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UnrealLightmass-CoreUObject.dll						%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UnrealLightmass-Json.dll								%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UnrealLightmass-Messaging.dll							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UnrealLightmass-Projects.dll							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UnrealLightmass-Serialization.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UnrealLightmass-SwarmInterface.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%embree.dll												%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%tbb.dll												%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%tbbmalloc.dll											%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%AgentInterface.dll										%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%..\DotNET\AgentInterface.dll							%PackageEngineBinPath%..\DotNET\
xcopy /e /y %UE4BinPath%..\DotNET\DotNETUtilities.dll							%PackageEngineBinPath%..\DotNET\
xcopy /e /y %UE4BinPath%..\DotNET\SwarmAgent.exe								%PackageEngineBinPath%..\DotNET\
xcopy /e /y %UE4BinPath%..\DotNET\SwarmCommonUtils.dll							%PackageEngineBinPath%..\DotNET\
xcopy /e /y %UE4BinPath%..\DotNET\SwarmCoordinatorInterface.dll				%PackageEngineBinPath%..\DotNET\
xcopy /e /y %UE4BinPath%..\DotNET\SwarmInterface.dll							%PackageEngineBinPath%..\DotNET\
xcopy /e /y %UE4BinPath%..\DotNET\UnrealControls.dll							%PackageEngineBinPath%..\DotNET\

xcopy /e /y %UE4BinPath%ShaderCompileWorker.exe								%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Projects.dll						%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ApplicationCore.dll				%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Core.dll							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderCore.dll						%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-RenderCore.dll						%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-RHI.dll							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Json.dll							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderCompilerCommon.dll			%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-LauncherPlatform.dll				%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderFormatD3D.dll				%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderFormatOpenGL.dll				%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderPreprocessor.dll				%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-TargetPlatform.dll					%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%..\ThirdParty\Windows\DirectX\x64\d3dcompiler_47.dll	%PackageEngineBinPath%..\ThirdParty\Windows\DirectX\x64\
xcopy /e /y %UE4BinPath%..\..\Shaders\*.*										%PackageEngineBinPath%..\..\Shaders\

xcopy /e /y %ProjectPluginPath%XRRenderer\ThirdParty\*.*         	%PackagePluginPath%XRRenderer\ThirdParty /i

xcopy /e /y %UE4BinPath%ShaderCompileWorker-Win64-Debug.exe									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ApplicationCore-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Core-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Json-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-LauncherPlatform-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Projects-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-RenderCore-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-RHI-Win64-Debug.dll								%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderCompilerCommon-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderCore-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderFormatD3D-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderFormatOpenGL-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderPreprocessor-Win64-Debug.dll									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-TargetPlatform-Win64-Debug.dll									%PackageEngineBinPath%

xcopy /e /y %UE4BinPath%ShaderCompileWorker-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ApplicationCore-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Core-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Json-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-LauncherPlatform-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-Projects-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-RenderCore-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-RHI-Win64-Debug.pdb								%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderCompilerCommon-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderCore-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderFormatD3D-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderFormatOpenGL-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-ShaderPreprocessor-Win64-Debug.pdb									%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%ShaderCompileWorker-TargetPlatform-Win64-Debug.pdb									%PackageEngineBinPath%

xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\APEX_ClothingCHECKED_x64.dll		 		%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\APEX_DestructibleCHECKED_x64.dll		 	%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\APEX_LegacyCHECKED_x64.dll		 		%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\ApexFrameworkCHECKED_x64.dll		 		%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\NvClothCHECKED_x64.dll		 			%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\PhysX3CHECKED_x64.dll		 				%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\PhysX3CommonCHECKED_x64.dll		 		%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\PhysX3CookingCHECKED_x64.dll		 		%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\PxFoundationCHECKED_x64.dll		 		%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\PhysX\Win64\VS2015\PxPvdSDKCHECKED_x64.dll		 			%PackageEngineBinPath%..\ThirdParty\PhysX\Win64\VS2015\
xcopy /e /y %UE4BinPath%..\ThirdParty\nvTextureTools\Win64\nvtt_64.dll		 						%PackageEngineBinPath%..\ThirdParty\nvTextureTools\Win64\

xcopy /e /y %UE4PluginPath%2D\Paper2D\Binaries\Win64\UE4Editor-Paper2D-Win64-Debug.dll		 						%PackageEnginePluginPath%2D\Paper2D\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Blendables\LightPropagationVolume\Binaries\Win64\UE4Editor-LightPropagationVolumeRuntime-Win64-Debug.dll		 						%PackageEnginePluginPath%Blendables\LightPropagationVolume\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Editor\FacialAnimation\Binaries\Win64\UE4Editor-FacialAnimation-Win64-Debug.dll		 						%PackageEnginePluginPath%Editor\FacialAnimation\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Experimental\CharacterAI\Binaries\Win64\UE4Editor-CharacterAI-Win64-Debug.dll		 						%PackageEnginePluginPath%Experimental\CharacterAI\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Experimental\HTML5Networking\Binaries\Win64\UE4Editor-HTML5Networking-Win64-Debug.dll		 						%PackageEnginePluginPath%Experimental\HTML5Networking\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\ImgMedia\Binaries\Win64\UE4Editor-ImgMedia-Win64-Debug.dll		 						%PackageEnginePluginPath%Media\ImgMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\ImgMedia\Binaries\Win64\UE4Editor-ImgMediaFactory-Win64-Debug.dll		 				%PackageEnginePluginPath%Media\ImgMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\ImgMedia\Binaries\Win64\UE4Editor-OpenExrWrapper-Win64-Debug.dll		 					%PackageEnginePluginPath%Media\ImgMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\AvfMedia\Binaries\Win64\UE4Editor-AvfMediaFactory-Win64-Debug.dll		 					%PackageEnginePluginPath%Media\AvfMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\MediaCompositing\Binaries\Win64\UE4Editor-MediaCompositing-Win64-Debug.dll		 					%PackageEnginePluginPath%Media\MediaCompositing\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\WmfMedia\Binaries\Win64\UE4Editor-WmfMedia-Win64-Debug.dll		 					%PackageEnginePluginPath%Media\WmfMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\WmfMedia\Binaries\Win64\UE4Editor-WmfMediaFactory-Win64-Debug.dll		 					%PackageEnginePluginPath%Media\WmfMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Messaging\TcpMessaging\Binaries\Win64\UE4Editor-TcpMessaging-Win64-Debug.dll		 					%PackageEnginePluginPath%Messaging\TcpMessaging\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Messaging\UdpMessaging\Binaries\Win64\UE4Editor-UdpMessaging-Win64-Debug.dll		 					%PackageEnginePluginPath%Messaging\UdpMessaging\Binaries\Win64\
xcopy /e /y %UE4PluginPath%MovieScene\ActorSequence\Binaries\Win64\UE4Editor-ActorSequence-Win64-Debug.dll		 		%PackageEnginePluginPath%MovieScene\ActorSequence\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Online\OnlineSubsystem\Binaries\Win64\UE4Editor-OnlineSubsystem-Win64-Debug.dll		 		%PackageEnginePluginPath%Online\OnlineSubsystem\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Online\OnlineSubsystemNull\Binaries\Win64\UE4Editor-OnlineSubsystemNull-Win64-Debug.dll		%PackageEnginePluginPath%Online\OnlineSubsystemNull\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Online\OnlineSubsystemUtils\Binaries\Win64\UE4Editor-OnlineSubsystemUtils-Win64-Debug.dll		%PackageEnginePluginPath%Online\OnlineSubsystemUtils\Binaries\Win64\

xcopy /e /y %UE4PluginPath%Runtime\AndroidPermission\Binaries\Win64\UE4Editor-AndroidPermission-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\AndroidPermission\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\ArchVisCharacter\Binaries\Win64\UE4Editor-ArchVisCharacter-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\ArchVisCharacter\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\CableComponent\Binaries\Win64\UE4Editor-CableComponent-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\CableComponent\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\CustomMeshComponent\Binaries\Win64\UE4Editor-CustomMeshComponent-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\CustomMeshComponent\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\ExampleDeviceProfileSelector\Binaries\Win64\UE4Editor-ExampleDeviceProfileSelector-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\ExampleDeviceProfileSelector\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\ImmediatePhysics\Binaries\Win64\UE4Editor-ImmediatePhysics-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\ImmediatePhysics\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\LocationServicesBPLibrary\Binaries\Win64\UE4Editor-LocationServicesBPLibrary-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\LocationServicesBPLibrary\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\MobilePatchingUtils\Binaries\Win64\UE4Editor-MobilePatchingUtils-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\MobilePatchingUtils\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\PhysXVehicles\Binaries\Win64\UE4Editor-PhysXVehicles-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\PhysXVehicles\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\ProceduralMeshComponent\Binaries\Win64\UE4Editor-ProceduralMeshComponent-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\ProceduralMeshComponent\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\RuntimePhysXCooking\Binaries\Win64\UE4Editor-RuntimePhysXCooking-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\RuntimePhysXCooking\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\Steam\SteamVR\Binaries\Win64\UE4Editor-SteamVR-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\Steam\SteamVR\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\Steam\SteamVR\Binaries\Win64\UE4Editor-SteamVRController-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\Steam\SteamVR\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\WindowsMoviePlayer\Binaries\Win64\UE4Editor-WindowsMoviePlayer-Win64-Debug.dll		 		%PackageEnginePluginPath%Runtime\WindowsMoviePlayer\Binaries\Win64\


xcopy /e /y %UE4PluginPath%2D\Paper2D\Binaries\Win64\UE4Editor-Paper2D-Win64-Debug.pdb		 						%PackageEnginePluginPath%2D\Paper2D\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Blendables\LightPropagationVolume\Binaries\Win64\UE4Editor-LightPropagationVolumeRuntime-Win64-Debug.pdb		 						%PackageEnginePluginPath%Blendables\LightPropagationVolume\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Editor\FacialAnimation\Binaries\Win64\UE4Editor-FacialAnimation-Win64-Debug.pdb		 						%PackageEnginePluginPath%Editor\FacialAnimation\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Experimental\CharacterAI\Binaries\Win64\UE4Editor-CharacterAI-Win64-Debug.pdb		 						%PackageEnginePluginPath%Experimental\CharacterAI\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Experimental\HTML5Networking\Binaries\Win64\UE4Editor-HTML5Networking-Win64-Debug.pdb		 						%PackageEnginePluginPath%Experimental\HTML5Networking\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\ImgMedia\Binaries\Win64\UE4Editor-ImgMedia-Win64-Debug.pdb		 						%PackageEnginePluginPath%Media\ImgMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\ImgMedia\Binaries\Win64\UE4Editor-ImgMediaFactory-Win64-Debug.pdb		 				%PackageEnginePluginPath%Media\ImgMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\ImgMedia\Binaries\Win64\UE4Editor-OpenExrWrapper-Win64-Debug.pdb		 					%PackageEnginePluginPath%Media\ImgMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\AvfMedia\Binaries\Win64\UE4Editor-AvfMediaFactory-Win64-Debug.pdb		 					%PackageEnginePluginPath%Media\AvfMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\MediaCompositing\Binaries\Win64\UE4Editor-MediaCompositing-Win64-Debug.pdb		 					%PackageEnginePluginPath%Media\MediaCompositing\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\WmfMedia\Binaries\Win64\UE4Editor-WmfMedia-Win64-Debug.pdb		 					%PackageEnginePluginPath%Media\WmfMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Media\WmfMedia\Binaries\Win64\UE4Editor-WmfMediaFactory-Win64-Debug.pdb		 					%PackageEnginePluginPath%Media\WmfMedia\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Messaging\TcpMessaging\Binaries\Win64\UE4Editor-TcpMessaging-Win64-Debug.pdb		 					%PackageEnginePluginPath%Messaging\TcpMessaging\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Messaging\UdpMessaging\Binaries\Win64\UE4Editor-UdpMessaging-Win64-Debug.pdb		 					%PackageEnginePluginPath%Messaging\UdpMessaging\Binaries\Win64\
xcopy /e /y %UE4PluginPath%MovieScene\ActorSequence\Binaries\Win64\UE4Editor-ActorSequence-Win64-Debug.pdb		 		%PackageEnginePluginPath%MovieScene\ActorSequence\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Online\OnlineSubsystem\Binaries\Win64\UE4Editor-OnlineSubsystem-Win64-Debug.pdb		 		%PackageEnginePluginPath%Online\OnlineSubsystem\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Online\OnlineSubsystemNull\Binaries\Win64\UE4Editor-OnlineSubsystemNull-Win64-Debug.pdb		%PackageEnginePluginPath%Online\OnlineSubsystemNull\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Online\OnlineSubsystemUtils\Binaries\Win64\UE4Editor-OnlineSubsystemUtils-Win64-Debug.pdb		%PackageEnginePluginPath%Online\OnlineSubsystemUtils\Binaries\Win64\

xcopy /e /y %UE4PluginPath%Runtime\AndroidPermission\Binaries\Win64\UE4Editor-AndroidPermission-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\AndroidPermission\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\ArchVisCharacter\Binaries\Win64\UE4Editor-ArchVisCharacter-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\ArchVisCharacter\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\CableComponent\Binaries\Win64\UE4Editor-CableComponent-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\CableComponent\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\CustomMeshComponent\Binaries\Win64\UE4Editor-CustomMeshComponent-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\CustomMeshComponent\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\ExampleDeviceProfileSelector\Binaries\Win64\UE4Editor-ExampleDeviceProfileSelector-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\ExampleDeviceProfileSelector\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\ImmediatePhysics\Binaries\Win64\UE4Editor-ImmediatePhysics-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\ImmediatePhysics\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\LocationServicesBPLibrary\Binaries\Win64\UE4Editor-LocationServicesBPLibrary-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\LocationServicesBPLibrary\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\MobilePatchingUtils\Binaries\Win64\UE4Editor-MobilePatchingUtils-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\MobilePatchingUtils\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\PhysXVehicles\Binaries\Win64\UE4Editor-PhysXVehicles-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\PhysXVehicles\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\ProceduralMeshComponent\Binaries\Win64\UE4Editor-ProceduralMeshComponent-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\ProceduralMeshComponent\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\RuntimePhysXCooking\Binaries\Win64\UE4Editor-RuntimePhysXCooking-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\RuntimePhysXCooking\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\Steam\SteamVR\Binaries\Win64\UE4Editor-SteamVR-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\Steam\SteamVR\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\Steam\SteamVR\Binaries\Win64\UE4Editor-SteamVRController-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\Steam\SteamVR\Binaries\Win64\
xcopy /e /y %UE4PluginPath%Runtime\WindowsMoviePlayer\Binaries\Win64\UE4Editor-WindowsMoviePlayer-Win64-Debug.pdb		 		%PackageEnginePluginPath%Runtime\WindowsMoviePlayer\Binaries\Win64\


xcopy /e /y %UE4BinPath%UE4Editor-XmlParser-Win64-Debug.dll 							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ImageCore-Win64-Debug.dll 							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ImageDownload-Win64-Debug.dll 						%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Voice-Win64-Debug.dll 								%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Advertising-Win64-Debug.dll 						%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AIModule-Win64-Debug.dll                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Analytics-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AnalyticsET-Win64-Debug.dll                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AnimationCore-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AnimGraphRuntime-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AppFramework-Win64-Debug.dll                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ApplicationCore-Win64-Debug.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AssetRegistry-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AudioMixer-Win64-Debug.dll                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AudioMixerXAudio2-Win64-Debug.dll                  %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AutomationController-Win64-Debug.dll               %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AutomationMessages-Win64-Debug.dll                 %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AutomationWorker-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AVIWriter-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-BuildPatchServices-Win64-Debug.dll                 %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-CinematicCamera-Win64-Debug.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ClothingSystemRuntime-Win64-Debug.dll              %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ClothingSystemRuntimeInterface-Win64-Debug.dll     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-CookedIterativeFile-Win64-Debug.dll                %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Core-Win64-Debug.dll                               %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-CoreUObject-Win64-Debug.dll                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-D3D11RHI-Win64-Debug.dll                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-D3D12RHI-Win64-Debug.dll                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-DatabaseSupport-Win64-Debug.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-DesktopPlatform-Win64-Debug.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-EditorStyle-Win64-Debug.dll                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Engine-Win64-Debug.dll                             %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-EngineMessages-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-EngineSettings-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Foliage-Win64-Debug.dll                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-GameplayDebugger-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-GameplayTags-Win64-Debug.dll                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-GameplayTasks-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-GeometryCache-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-HardwareSurvey-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-HeadMountedDisplay-Win64-Debug.dll                 %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-HTTP-Win64-Debug.dll                               %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-HttpNetworkReplayStreaming-Win64-Debug.dll         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ImageWrapper-Win64-Debug.dll                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-InputCore-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-InputDevice-Win64-Debug.dll                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Json-Win64-Debug.dll                               %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-JsonUtilities-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Landscape-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-LauncherPlatform-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-LevelSequence-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Localization-Win64-Debug.dll                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MaterialShaderQualitySettings-Win64-Debug.dll      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Media-Win64-Debug.dll                              %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MediaAssets-Win64-Debug.dll                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MediaUtils-Win64-Debug.dll                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MessageLog-Win64-Debug.dll                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Messaging-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MessagingCommon-Win64-Debug.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MoviePlayer-Win64-Debug.dll                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MovieScene-Win64-Debug.dll                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MovieSceneCapture-Win64-Debug.dll                  %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MovieSceneTracks-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MRMesh-Win64-Debug.dll                             %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Navmesh-Win64-Debug.dll                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-NetworkFile-Win64-Debug.dll                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Networking-Win64-Debug.dll                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-NetworkReplayStreaming-Win64-Debug.dll             %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-NullDrv-Win64-Debug.dll                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-NullNetworkReplayStreaming-Win64-Debug.dll         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-OpenGLDrv-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Overlay-Win64-Debug.dll                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-PacketHandler-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-PakFile-Win64-Debug.dll                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-PhysXCooking-Win64-Debug.dll                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ProfilerMessages-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ProfilerService-Win64-Debug.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Projects-Win64-Debug.dll                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-RealtimeProfiler-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ReliabilityHandlerComponent-Win64-Debug.dll        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-RenderCore-Win64-Debug.dll                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Renderer-Win64-Debug.dll                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-RHI-Win64-Debug.dll                                %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SandboxFile-Win64-Debug.dll                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ScreenShotComparisonTools-Win64-Debug.dll          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Serialization-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SessionMessages-Win64-Debug.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SessionServices-Win64-Debug.dll                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ShaderCore-Win64-Debug.dll                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Slate-Win64-Debug.dll                              %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SlateCore-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SlateNullRenderer-Win64-Debug.dll                  %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SlateReflector-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SlateRHIRenderer-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Sockets-Win64-Debug.dll                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SourceControl-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SSL-Win64-Debug.dll                                %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-StreamingFile-Win64-Debug.dll                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-StreamingPauseRendering-Win64-Debug.dll            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SynthBenchmark-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TargetPlatform-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TaskGraph-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TextureCompressor-Win64-Debug.dll                  %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-UMG-Win64-Debug.dll                                %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-UnrealEdMessages-Win64-Debug.dll                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-UtilityShaders-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-VulkanRHI-Win64-Debug.dll                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-XAudio2-Win64-Debug.dll                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-RawMesh-Win64-Debug.dll                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TargetPlatform-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SwarmInterface-Win64-Debug.dll                     %PackageEngineBinPath%

xcopy /e /y %UE4BinPath%UE4Editor-ShaderFormatD3D-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ShaderPreprocessor-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ShaderCompilerCommon-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-DerivedDataCache-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-WindowsTargetPlatform-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TextureFormatDXT-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TextureFormatUncompressed-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-WebBrowser-Win64-Debug.dll                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-CEF3Utils-Win64-Debug.dll                     %PackageEngineBinPath%


xcopy /e /y %UE4BinPath%UE4Editor-WebBrowser-Win64-Debug.pdb 							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-CEF3Utils-Win64-Debug.pdb 							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-XmlParser-Win64-Debug.pdb 							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ImageCore-Win64-Debug.pdb 							%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ImageDownload-Win64-Debug.pdb 						%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Voice-Win64-Debug.pdb 								%PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Advertising-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AIModule-Win64-Debug.pdb                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Analytics-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AnalyticsET-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AnimationCore-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AnimGraphRuntime-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AppFramework-Win64-Debug.pdb                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ApplicationCore-Win64-Debug.pdb                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AssetRegistry-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AudioMixer-Win64-Debug.pdb                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AudioMixerXAudio2-Win64-Debug.pdb                  %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AutomationController-Win64-Debug.pdb               %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AutomationMessages-Win64-Debug.pdb                 %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AutomationWorker-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-AVIWriter-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-BuildPatchServices-Win64-Debug.pdb                 %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-CinematicCamera-Win64-Debug.pdb                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ClothingSystemRuntime-Win64-Debug.pdb              %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ClothingSystemRuntimeInterface-Win64-Debug.pdb     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-CookedIterativeFile-Win64-Debug.pdb                %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Core-Win64-Debug.pdb                               %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-CoreUObject-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-D3D11RHI-Win64-Debug.pdb                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-D3D12RHI-Win64-Debug.pdb                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-DatabaseSupport-Win64-Debug.pdb                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-DesktopPlatform-Win64-Debug.pdb                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-EditorStyle-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Engine-Win64-Debug.pdb                             %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-EngineMessages-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-EngineSettings-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Foliage-Win64-Debug.pdb                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-GameplayDebugger-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-GameplayTags-Win64-Debug.pdb                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-GameplayTasks-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-GeometryCache-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-HardwareSurvey-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-HeadMountedDisplay-Win64-Debug.pdb                 %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-HTTP-Win64-Debug.pdb                               %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-HttpNetworkReplayStreaming-Win64-Debug.pdb         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ImageWrapper-Win64-Debug.pdb                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-InputCore-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-InputDevice-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Json-Win64-Debug.pdb                               %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-JsonUtilities-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Landscape-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-LauncherPlatform-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-LevelSequence-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Localization-Win64-Debug.pdb                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MaterialShaderQualitySettings-Win64-Debug.pdb      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Media-Win64-Debug.pdb                              %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MediaAssets-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MediaUtils-Win64-Debug.pdb                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MessageLog-Win64-Debug.pdb                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Messaging-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MessagingCommon-Win64-Debug.pdb                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MoviePlayer-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MovieScene-Win64-Debug.pdb                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MovieSceneCapture-Win64-Debug.pdb                  %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MovieSceneTracks-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-MRMesh-Win64-Debug.pdb                             %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Navmesh-Win64-Debug.pdb                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-NetworkFile-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Networking-Win64-Debug.pdb                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-NetworkReplayStreaming-Win64-Debug.pdb             %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-NullDrv-Win64-Debug.pdb                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-NullNetworkReplayStreaming-Win64-Debug.pdb         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-OpenGLDrv-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Overlay-Win64-Debug.pdb                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-PacketHandler-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-PakFile-Win64-Debug.pdb                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-PhysXCooking-Win64-Debug.pdb                       %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ProfilerMessages-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ProfilerService-Win64-Debug.pdb                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Projects-Win64-Debug.pdb                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-RealtimeProfiler-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ReliabilityHandlerComponent-Win64-Debug.pdb        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-RenderCore-Win64-Debug.pdb                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Renderer-Win64-Debug.pdb                           %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-RHI-Win64-Debug.pdb                                %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SandboxFile-Win64-Debug.pdb                        %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ScreenShotComparisonTools-Win64-Debug.pdb          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Serialization-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SessionMessages-Win64-Debug.pdb                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SessionServices-Win64-Debug.pdb                    %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ShaderCore-Win64-Debug.pdb                         %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Slate-Win64-Debug.pdb                              %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SlateCore-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SlateNullRenderer-Win64-Debug.pdb                  %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SlateReflector-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SlateRHIRenderer-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-Sockets-Win64-Debug.pdb                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SourceControl-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SSL-Win64-Debug.pdb                                %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-StreamingFile-Win64-Debug.pdb                      %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-StreamingPauseRendering-Win64-Debug.pdb            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SynthBenchmark-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TargetPlatform-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TaskGraph-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TextureCompressor-Win64-Debug.pdb                  %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-UMG-Win64-Debug.pdb                                %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-UnrealEdMessages-Win64-Debug.pdb                   %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-UtilityShaders-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-VulkanRHI-Win64-Debug.pdb                          %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-XAudio2-Win64-Debug.pdb                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-RawMesh-Win64-Debug.pdb                            %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TargetPlatform-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-SwarmInterface-Win64-Debug.pdb                     %PackageEngineBinPath%

xcopy /e /y %UE4BinPath%UE4Editor-ShaderFormatD3D-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ShaderPreprocessor-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-ShaderCompilerCommon-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-DerivedDataCache-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-WindowsTargetPlatform-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TextureFormatDXT-Win64-Debug.pdb                     %PackageEngineBinPath%
xcopy /e /y %UE4BinPath%UE4Editor-TextureFormatUncompressed-Win64-Debug.pdb                     %PackageEngineBinPath%

pause
